### PR TITLE
Edit ProjectCard

### PR DESCRIPTION
**Pull request by maksim-luzin**

### CODE REVIEW

**Review by yevhenii-moroziuk — COMMENTED** [review]
I would check BE side because it should return the correct data.

**Comment by maksim-luzin** [comment]
dfgaesrtger5tg

**Comment by maksim-luzin** [comment]
asdfseagfttaer54hgye5rtyh

**Comment by maksim-luzin** [comment]
asdfseagfttaer54hgye5rtyhreergf

**Comment by maksim-luzin** [comment]
dfgaesrtger5tg

**Comment by maksim-luzin** [comment]
asdfseagfttaer54hgye5rtyhreergf

**Review by yevhenii-moroziuk — APPROVED** [review]

**Comment by mtseluiko** [comment]
Why so many deleted?

**Review by mtseluiko — CHANGES_REQUESTED** [review]
This PR will delete many features and brake develop

**Pull request merged**
