### PR TITLE
Add metadata for social networks

### PR DESCRIPTION
**Pull request by maksim-luzin**

### CODE REVIEW

**Review by yevhenii-moroziuk — COMMENTED** [review]
Looks good, but would be nice to have a localized text

**Comment by maksim-luzin** [comment]
Added localization and images on free hosting http://litepic.ru

**Comment by maksim-luzin** [comment]
[en_US](http://s1.litepic.ru/121082524293df507f813f618cae.png)
[ua_UA](http://s1.litepic.ru/121082524d7bdd3f6f2bc8898345.png)

**Comment by maksim-luzin** [comment]
Picture_En

**Comment by maksim-luzin** [comment]
Picture_Ua

**Review by yevhenii-moroziuk — APPROVED** [review]

**Pull request merged**
